.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH hsize-generate-manpages 1  "manpages " 
.SH NAME
hsize\-generate\-manpages \- Roff manpages
.SH SYNOPSIS
\fBhsize generate manpages\fR [\fB\-o\fR|\fB\-\-output\-directory\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Roff manpages
.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-output\-directory\fR \fI<OUTPUT_DIRECTORY>\fR [default: .]
Directory to save generated manpages
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
