.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH hsize 1  "hsize 0.1.0" 
.SH NAME
hsize \- Convert file sizes to and from human\-readable units
.SH SYNOPSIS
\fBhsize\fR [\fB\-p\fR|\fB\-\-precision\fR] [\fB\-f\fR|\fB\-\-from\-scale\fR] [\fB\-B\fR|\fB\-\-from\-binary\fR] [\fB\-t\fR|\fB\-\-to\-scale\fR] [\fB\-b\fR|\fB\-\-to\-binary\fR] [\fB\-e\fR|\fB\-\-scientific\-notation\fR] [\fB\-s\fR|\fB\-\-separator\fR] [\fB\-n\fR|\fB\-\-no\-b\-suffix\fR] [\fB\-S\fR|\fB\-\-skip\-short\-numbers\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fISIZES\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Convert file sizes to and from human\-readable units
.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-precision\fR \fI<PRECISION>\fR [default: 1]
Number of decimal places to display in the converted number
.TP
\fB\-f\fR, \fB\-\-from\-scale\fR \fI<SCALE>\fR
Size scale of the given numbers
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
b
.IP \(bu 2
k
.IP \(bu 2
m
.IP \(bu 2
g
.IP \(bu 2
t
.IP \(bu 2
p
.IP \(bu 2
e
.IP \(bu 2
z
.IP \(bu 2
y
.IP \(bu 2
r
.IP \(bu 2
q
.RE
.TP
\fB\-B\fR, \fB\-\-from\-binary\fR
Given numbers are powers of 2 (1K = 1024)
.TP
\fB\-t\fR, \fB\-\-to\-scale\fR \fI<SCALE>\fR
Size scale of the converted numbers
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
b
.IP \(bu 2
k
.IP \(bu 2
m
.IP \(bu 2
g
.IP \(bu 2
t
.IP \(bu 2
p
.IP \(bu 2
e
.IP \(bu 2
z
.IP \(bu 2
y
.IP \(bu 2
r
.IP \(bu 2
q
.RE
.TP
\fB\-b\fR, \fB\-\-to\-binary\fR
Converted numbers should be powers of 2 (1K = 1024)
.TP
\fB\-e\fR, \fB\-\-scientific\-notation\fR
Numbers should be displayed in scientific notation
.TP
\fB\-s\fR, \fB\-\-separator\fR \fI<SEPARATOR>\fR [default:  ]
Characters to put between the number and unit
.TP
\fB\-n\fR, \fB\-\-no\-b\-suffix\fR
Remove the \*(AqB\*(Aq from the end of the unit (MB \-> M)
.TP
\fB\-S\fR, \fB\-\-skip\-short\-numbers\fR
Skip converting numbers if they\*(Aqll end up being longer than the original
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
[\fISIZES\fR]

.SH SUBCOMMANDS
.TP
hsize\-replace(1)
Use regex to search and replace numbers
.TP
hsize\-generate(1)
Generate various shell command files
.SH VERSION
v0.1.0
