.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH hsize-generate-completions 1  "completions " 
.SH NAME
hsize\-generate\-completions \- Shell completions
.SH SYNOPSIS
\fBhsize generate completions\fR <\fB\-s\fR|\fB\-\-shell\fR> [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Shell completions
.SH OPTIONS
.TP
\fB\-s\fR, \fB\-\-shell\fR \fI<SHELL>\fR
Output completion files for the given shell
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
bash
.IP \(bu 2
elvish
.IP \(bu 2
fish
.IP \(bu 2
powershell
.IP \(bu 2
zsh
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
