.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH hsize-replace 1  "replace " 
.SH NAME
hsize\-replace \- Use regex to search and replace numbers
.SH SYNOPSIS
\fBhsize replace\fR [\fB\-r\fR|\fB\-\-regex\fR] [\fB\-U\fR|\fB\-\-multi\-line\fR] [\fB\-L\fR|\fB\-\-no\-right\-align\fR] [\fB\-i\fR|\fB\-\-in\-place\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIFILES\fR] 
.SH DESCRIPTION
Use regex to search and replace numbers
.SH OPTIONS
.TP
\fB\-r\fR, \fB\-\-regex\fR=\fIREGEX\fR [default: \\d+]
Regex to use for matching numbers
.RS
May also be specified with the \fBHSIZE_REGEX\fR environment variable. 
.RE
.TP
\fB\-U\fR, \fB\-\-multi\-line\fR
Enable multi\-line regex searching
.TP
\fB\-L\fR, \fB\-\-no\-right\-align\fR
Don\*(Aqt align converted sizes to the right
.RS
May also be specified with the \fBHSIZE_NO_RIGHT_ALIGN\fR environment variable. 
.RE
.TP
\fB\-i\fR, \fB\-\-in\-place\fR
Modify (search and replace) files in\-place
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIFILES\fR]

