cargo-features = ["profile-rustflags", "trim-paths"]

[package]
name = "hsize"
version = "1.0.0"
edition = "2021"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = "symbols"

[profile.small]
codegen-units = 1
debug = false
inherits = "release"
lto = true
opt-level = "z"
panic = "abort"
strip = "symbols"
trim-paths = "all"
rustflags = ["-Zlocation-detail=none"]

[profile.dev]
rustflags = ["-Zshare-generics"]

[dependencies]
clap = { version = "4.4", default-features = false, features = [
  "std",
  "derive",
] }
num-derive = "0.4"
num-traits = "0.2"
regex = { version = "1.10", default-features = false, features = [
  "unicode-perl",
] }
