cargo-features = ["profile-rustflags", "trim-paths"]

[package]
name = "hsize"
version = "1.0.0"
edition = "2021"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = "symbols"
trim-paths = "all"

[profile.small]
codegen-units = 1
debug = false
inherits = "release"
lto = true
opt-level = "z"
panic = "abort"
strip = "symbols"
rustflags = ["-Zlocation-detail=none"]

[profile.dev]
rustflags = ["-Zshare-generics"]

[dependencies]
clap = { version = "4", default-features = false, features = ["std", "derive"] }
num-derive = "0"
num-traits = "0"
regex = { version = "1", default-features = false, features = ["unicode-perl"] }
