[package]
name = "hsize"
version = "1.0.0"
edition = "2021"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = "symbols"

[dependencies]
atty = "0.2"
clap = { version = "4.4", features = ["derive"] }
num-derive = "0.4"
num-traits = "0.2"
regex = "1.10"
