[package]
name = "hsize"
version = "1.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
opt-level = 3

[dependencies]
atty = "0.2.14"
clap = { version = "4.4.4", features = ["derive"] }
num-derive = "0.3.3"
num-traits = "0.2.15"
