name: Build
on:
    push:
        paths:
            - "**.nix"
            - "**.rs"
            - Cargo.*
            - completions/**
            - flake.lock
            - man/**
    pull_request:
    workflow_dispatch:

jobs:
    hsize:
        name: hsize (${{ matrix.os }})
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                include:
                    - os: ubuntu-24.04
                    - os: ubuntu-24.04-arm

        steps:
            - name: Clone repository
              uses: actions/checkout@v6

            - name: Install Nix
              uses: DeterminateSystems/nix-installer-action@v22
              with:
                  extra-conf: |
                      log-lines = 500

            - name: Build Nix package
              run: nix build -L
