name: Build
on:
    push:
        paths:
            - "**.nix"
            - "**.rs"
            - Cargo.*
            - completions/**
            - flake.lock
            - man/**
    pull_request:
    workflow_dispatch:

jobs:
    hsize:
        name: hsize
        runs-on: ubuntu-22.04

        strategy:
            fail-fast: false
            matrix:
                include:
                    - system: aarch64-linux
                    - system: i686-linux
                    - system: x86_64-linux

        steps:
            - name: Clone repository
              uses: actions/checkout@v4

            - name: Install QEMU
              run: |
                  sudo apt update -y
                  sudo apt install -y qemu-user-static

            - name: Install Nix
              uses: DeterminateSystems/nix-installer-action@v20
              with:
                  extra-conf: |
                      log-lines = 500
                      substituters = https://cache.garnix.io
                      trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=

            - name: Build for ${{ matrix.system }}
              run: nix build -L --system ${{ matrix.system }}
